### ISSUE TITLE
Only runs on windows

### ISSUE THREAD

**Issue by DaMatrix** [Zee1234/CuberitePlugin-BungeeButtons#1]
Line 30 of main.lua uses backslashes . Those are only used for directory manes in Windows, *nix systems use forward slashes /.  This prevents the plugin from initializing correctly on *nix.

edit from The Future™️: wtf i'm stupid

**Comment by Zee1234** [comment]
Cuberite fixes that last I checked, as I tested this plugin largely on a linux system. At one point I even tested out plugins\BungeeButtons/test just to see if that worked, and it did.

However I'll double check that this is still the case.

**Comment by Zee1234** [comment]
Doublechecked. \ vs / gets fixed on windows, swapped globally to *nix standard.

**Comment by DaMatrix** [comment]
Huh, I tried it on windows and it worked fine, but rPi and another debian machine required for me to change it to / to work.

Sent from my Samsung device

-------- Original message --------

**Comment by Zee1234** [comment]
Could you check the new version on a Debian/rPi? I've only got access to RedHat variants atm.

**Comment by DaMatrix** [comment]
apt-get uptate and upgrade, then tried again.  Same problem. 

-------- Original message --------

**Comment by Zee1234** [comment]
? I don't think apt-get would upgrade the git clones or however you got them, would it?

**Comment by DaMatrix** [comment]
I'm running whatever the version was at 5:00 p.m. yesterday.

-------- Original message --------

**Comment by Zee1234** [comment]
Time zone..?

**Comment by DaMatrix** [comment]
CET Switzerland

**Comment by DaMatrix** [comment]
Seemingly fixed, closing
